### ISSUE TITLE
[feat] Create new data structure for new command system

### ISSUE THREAD

**Issue by san-ghun** [san-ghun/minishell#43]
As @miooo0o mentioned in #38 , we need a better implementation of the command system to parse commands more intuitively and efficiently. 
To handle specific character sequences, such as `""`, `''`, `;`, `$`, and more, I think it would be better to create a new data structure for the new command line system.
So, we may replace our current tokenized string-based command line system with a struct-based command line system.

- [x] Create new `struct` to store data.
- [x] #46
- [x] Create handlers for `""`. #15 
- [x] Create handlers for `''`. #14 
- [x] ~~Create handlers for `;`.~~ #17 
- [x] Create handlers for `$`.

**Comment by san-ghun** [comment]
Suggesting a new prototype.
```c
typedef struct s_sent
{
	void			*content;  // optional
	str			*cmd;  // actual cmd such as, 'echo' 'cd' 'grep'
	str			*args;  // arguments for cmd
	int			prefix;  // indicator for prefix type such as, 'redirect' 'pipe' ...
	int			suffix;  // indicator for suffix type such as, 'redirect' 'pipe' ...
	struct s_sent		*prev;  // pointer to previous node
	struct s_sent		*next;  // pointer to next node
}				t_sent;
```

**Comment by miooo0o** [comment]
I talked to YY about structs, and she said that we don't need to split commands because we need both the command and the string to be executed when we eventually execute it.  Now that I think about it, I remembered doing that for the pipex project. What do you think?

**Comment by miooo0o** [comment]
Oh, and she told me to use malloc - she started out using arrays and then switched.

**Comment by san-ghun** [comment]
```bash
typedef struct s_sent
{
	char		**token;  // Save the cmd, its arguments, and enough to run at once, truncated by a semicolon.
	int			is_redir;  // indicator for 'redirect' 
	int			is_pipe;  // indicator for 'pipe' and `;` and `\n`
	struct s_sent		*prev;  // pointer to previous node
	struct s_sent		*next;  // pointer to next node
}
```

**Comment by miooo0o** [comment]
```
$ echo this here          hey 
this here hey
```

```
$ echo this here hey
this here hey
```

[Suggestion] Change the format of the trim when tokenised.

anything within " " will be tokenised with the double quotes removed when tokenising. 

`int			is_quote; `
This is also unnecessary.
